[package]
name = "soc-cover-generator"
version = "1.0.0"
description = "SOC report cover generator"
authors = ["local"]
edition = "2021"

[lib]
name = "soc_cover_generator_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
